### ISSUE TITLE
Single main config file

### ISSUE THREAD

**Issue by hkir-dev** [OBASKTools/obask#26]
Config files are very scattered. A single config that drives the basic setup would be better. 

```yaml
full_ontologies: 
  - http://purl.obolibrary.org/obo/cl.owl
  - http://purl.obolibrary.org/obo/uberon/uberon-base.owl
slices:
  - http://purl.obolibrary.org/obo/ro.owl
classifications:
  - label: Cell
    classes:
      - CL:0000000
  - label: Nervous_system
    classes:
      - RO:0002131 some FBbt:00005093
      - FBbt:00005155
curie_map:
  RO: http://purl.obolibrary.org/obo/RO_
  CL: http://purl.obolibrary.org/obo/CL_
  FBbt: http://purl.obolibrary.org/obo/fbbt#
output:
  solr_index: true
  search_api: true
  knowledge_graph: true
```

We can generate current config files from this main config to make minimal changes on the pipeline.
